### ISSUE TITLE
UnicodeDecodeError: 'utf-8'

### ISSUE THREAD

**Issue by robbrad** [azrdev/rtl433_influx#1]
Im getting the following error when running

~~~sh
$ python3 rtl433json_to_influx.py /usr/local/bin/rtl_433

Traceback (most recent call last):
  File "rtl433json_to_influx.py", line 83, in <module>
    for line in source:
  File "/usr/lib/python3.6/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xdb in position 25: invalid continuation byte

**Comment by azrdev** [comment]
@robbrad the script is trying to read from the rtl_433 binary, which is not valid UTF8 text (obviously). Instead, run `/usr/local/bin/rtl_433 | python3 rtl433json_to_influx.py` and/or use the supplied systemd files, which run these two as (two separate) services, which communicate through the named pipe `/var/run/rtl433`.

**Comment by robbrad** [comment]
Brilliant your a star ! got it working

**Comment by robbrad** [comment]
Sorry to contact on here but didnt have your email.

Do you know why the rtl433json_to_influx.service ends up as (code=exited, status=0/SUCCESS) - can I just run it continuously ?

**Comment by azrdev** [comment]
> Do you know why the rtl433json_to_influx.service ends up as (code=exited, status=0/SUCCESS) - can I just run it continuously ?

it should keep running and consuming from the pipe `/var/run/rtl433`. If there is no log output (`journalctl -u rtl433json_to_influx -e`) probably the pipe has run empty, but I'm not sure why -- in my case that never happened, as far as I can tell. Have you modified the script or the service files in some way? Maybe you find a clue in the log of the rtl_433 service?

**Comment by robbrad** [comment]
Its my fault in the way I had it running - I have explicitly followed your instructions and it is now working - this is a super little solution. nice work!
