### ISSUE TITLE
warning to use /run instead /var/run in tmpfiles.d

### ISSUE THREAD

**Issue by azrdev** [azrdev/rtl433_influx#4]
> Hello, complete novice here... I've got RTL433 setup on a Pi - works with the device codes if I run it manually. Followed your instructions to the awesome code you wrote to try and get some 433 devices shipped to my influxdb but having issues with it not appearing to run. Getting a message about /var/run not being top level enough (or similar). Tried changing all /var/run links to /run but still no dice. Don't suppose you have any ideas?

_Originally posted by @t3n-matthomas in https://github.com/azrdev/rtl433_influx/pull/2#issuecomment-535416902_

**Comment by azrdev** [comment]
@t3n-matthomas I moved this to an extra issue, because it has nothing to do with the pull request you commented on.

> Don't suppose you have any ideas?

the actual error message(s) you get would be a great help. also, what OS are you running -- raspbian (paste `cat /etc/os-release` if you're unsure)? Usually also a good idea to update the system: `apt update && apt upgrade`.

**Comment by t3n-matthomas** [comment]
Many apologies - I figured it was the wrong place but wasn't sure where to create.

Release info:

PRETTY_NAME="Raspbian GNU/Linux 10 (buster)"
NAME="Raspbian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"

I think I'm going to start from scratch and try again as now I'm getting an error when running
`/usr/bin/python3 /home/rtl433sdr/bin/rtl433json_to_influx.py /run/rtl433`
Which states `ModuleNotFoundError: No module named 'influxdb'`
Even though InfluxDB is installed and running.
Again - sorry for being a complete novice at Linux/433 - well versed in Windows/MacOS but Linux is new to me, just need to add this one sensor to Influx.

**Comment by azrdev** [comment]
>  Which states `ModuleNotFoundError: No module named 'influxdb'`

That refers to the `influxdb` python module needed to talk to the database, not the db itself.

**Comment by t3n-matthomas** [comment]
I guessed as much - I already ran `sudo apt-get install python-influxdb` which completed without errors. I'll start with a fresh RPi install and try again as I must have messed something up along the way.

**Comment by t3n-matthomas** [comment]
OK so I started with a fresh build of Raspbian and followed this guide to get rtlsdr and rtl433 installed: [http://www.sensorsiot.org/install-rtl_433-for-a-sdr-rtl-dongle-on-a-raspberry-pi/](http://www.sensorsiot.org/install-rtl_433-for-a-sdr-rtl-dongle-on-a-raspberry-pi/)

The error I get when trying to run `systemd-tempfiles --create` is `[/etc/tmpfiles.d/systemd-tmpfiles.rtl433.conf:1] Line references path below legacy directory /var/run/, updating /var/run/rtl433 → /run/rtl433; please update the tmpfiles.d/ drop-in file accordingly.`

**Comment by t3n-matthomas** [comment]
> OK so I started with a fresh build of Raspbian and followed this guide to get rtlsdr and rtl433 installed: http://www.sensorsiot.org/install-rtl_433-for-a-sdr-rtl-dongle-on-a-raspberry-pi/
> 
> The error I get when trying to run `systemd-tempfiles --create` is `[/etc/tmpfiles.d/systemd-tmpfiles.rtl433.conf:1] Line references path below legacy directory /var/run/, updating /var/run/rtl433 → /run/rtl433; please update the tmpfiles.d/ drop-in file accordingly.`

After re-reading this, can I take it this is just a warning and not an error stopping anything or do you think I need to take action to rectify?

**Comment by t3n-matthomas** [comment]
> > OK so I started with a fresh build of Raspbian and followed this guide to get rtlsdr and rtl433 installed: http://www.sensorsiot.org/install-rtl_433-for-a-sdr-rtl-dongle-on-a-raspberry-pi/
> > The error I get when trying to run `systemd-tempfiles --create` is `[/etc/tmpfiles.d/systemd-tmpfiles.rtl433.conf:1] Line references path below legacy directory /var/run/, updating /var/run/rtl433 → /run/rtl433; please update the tmpfiles.d/ drop-in file accordingly.`
> 
> After re-reading this, can I take it this is just a warning and not an error stopping anything or do you think I need to take action to rectify?

Annnnd after seeing data flowing into InfluxDB you can definitely close this marking it as "utter fool/Linux novice". Sorry to have disturbed you and thanks again for some great code. Do you have a donation link or anything like that?

**Comment by azrdev** [comment]
Absolutely no problem with asking basic or any kind of questions to get going! Glad you could help yourself before I saw your follow up, good luck with your further project. I don't have a financial input of this kind, and honestly wouldn't think of it being appropriate for such a quick'n'dirty script thrown to github… but I can only ask for you to publish any code,docs,tutorial or similar that emerges from your project, so others can benefit from it, too!

> Line references path below legacy directory /var/run/, updating /var/run/rtl433 → /run/rtl433; please update the tmpfiles.d/ drop-in file accordingly

That indeed is not a fatal error, just a suggestion how to update to newer conventions.
